run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  govet:
    enable-all: true
    disable:
      - fieldalignment # too strict

  gocyclo:
    min-complexity: 15

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 20

  cyclop:
    max-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
          - assign

  lll:
    line-length: 120

  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - i
      - j
      - k
      - v
      - id
      - ip
      - db
      - tx

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input

  staticcheck:
    go: "1.21"
    checks: ["all"]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - funlen
        - gocognit
        - cyclop
        - maintidx

    # Exclude some linters from running on example files.
    - path: examples/
      linters:
        - gosec
        - errcheck

    # Exclude some linters from running on cmd files.
    - path: cmd/
      linters:
        - gochecknoinits

    # Ignore magic numbers in tests
    - path: _test\.go
      linters:
        - gomnd

  exclude:
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - "Error return value of .((os\\.)?std(out|err)\\..*|print|printf|println|log\\.(Print|Panic|Fatal)|fmt\\.(Print|Printf|Println|Fprint|Fprintf|Fprintln)|fmt\\.(Print|Printf|Println|Fprint|Fprintf|Fprintln)) is not checked"

  max-issues-per-linter: 0
  max-same-issues: 0