---
- name: Install and Configure QEMU Guest Agent on Ubuntu VMs
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    qemu_guest_agent_config_path: /etc/qemu-ga
    qemu_guest_agent_service: qemu-guest-agent
    
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 300
      tags: 
        - packages
        - update

    - name: Install qemu-guest-agent package
      apt:
        name: qemu-guest-agent
        state: present
      notify: 
        - restart qemu-guest-agent
      tags:
        - packages
        - qemu-ga

    - name: Ensure systemd daemon is reloaded after package installation
      systemd:
        daemon_reload: yes
      tags:
        - packages
        - qemu-ga

    - name: Ensure qemu-guest-agent configuration directory exists
      file:
        path: "{{ qemu_guest_agent_config_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      tags:
        - config

    - name: Configure qemu-guest-agent
      copy:
        content: |
          # QEMU Guest Agent Configuration
          # This file is managed by Ansible
          
          # Enable logging (optional)
          # log-level=info
          # logfile=/var/log/qemu-ga.log
          
          # Network interface blacklist (if needed)
          # blacklist-rpc=guest-network-get-interfaces
          
          # Enable file system freeze/thaw for consistent snapshots
          # fsfreeze-hook=/etc/qemu-ga/fsfreeze-hook
        dest: "{{ qemu_guest_agent_config_path }}/qemu-ga.conf"
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify:
        - restart qemu-guest-agent
      tags:
        - config

    - name: Create fsfreeze hook script directory
      file:
        path: "{{ qemu_guest_agent_config_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      tags:
        - config

    - name: Install fsfreeze hook script for database VMs
      copy:
        content: |
          #!/bin/bash
          # QEMU Guest Agent fsfreeze hook script
          # This script is called before and after filesystem freeze operations
          
          LOGFILE="/var/log/fsfreeze-hook.log"
          
          log() {
              echo "$(date): $1" >> "$LOGFILE"
          }
          
          case "$1" in
              freeze)
                  log "Filesystem freeze requested"
                  # Add any pre-freeze operations here
                  # For databases, you might want to flush buffers
                  sync
                  ;;
              thaw)
                  log "Filesystem thaw requested"
                  # Add any post-thaw operations here
                  ;;
              *)
                  log "Unknown fsfreeze operation: $1"
                  exit 1
                  ;;
          esac
          
          exit 0
        dest: "{{ qemu_guest_agent_config_path }}/fsfreeze-hook"
        owner: root
        group: root
        mode: '0755'
      when: inventory_hostname in groups['databases'] or inventory_hostname in groups['cache']
      notify:
        - restart qemu-guest-agent
      tags:
        - config
        - fsfreeze

    - name: Enable and start qemu-guest-agent service
      systemd:
        name: "{{ qemu_guest_agent_service }}"
        enabled: yes
        state: started
        daemon_reload: yes
      tags:
        - service

    - name: Wait for service to be fully started
      wait_for:
        timeout: 10
      tags:
        - service

    - name: Verify service is enabled (double-check)
      systemd:
        name: "{{ qemu_guest_agent_service }}"
        enabled: yes
      tags:
        - service

    - name: Check qemu-guest-agent service status
      systemd:
        name: "{{ qemu_guest_agent_service }}"
      register: qemu_ga_status
      tags:
        - verify

    - name: Debug service status for troubleshooting
      debug:
        var: qemu_ga_status
      tags:
        - verify
        - debug

    - name: Display qemu-guest-agent version
      command: qemu-ga --version
      register: qemu_ga_version
      changed_when: false
      tags:
        - verify

    - name: Show qemu-guest-agent version
      debug:
        msg: "{{ inventory_hostname }}: {{ qemu_ga_version.stdout }}"
      tags:
        - verify

  handlers:
    - name: restart qemu-guest-agent
      systemd:
        name: "{{ qemu_guest_agent_service }}"
        state: restarted
        daemon_reload: yes