---
- name: Verify JFrog Artifactory Installation
  hosts: artifacts
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Check Artifactory service status
      systemd:
        name: artifactory
      register: artifactory_service_status

    - name: Display Artifactory service status
      debug:
        msg: |
          Artifactory Service Status:
          ==========================
          Status: {{ artifactory_service_status.status.ActiveState }}
          Enabled: {{ artifactory_service_status.status.UnitFileState }}
          Since: {{ artifactory_service_status.status.ActiveEnterTimestamp if artifactory_service_status.status.ActiveState == 'active' else 'N/A' }}

    - name: Check Artifactory process
      shell: ps aux | grep -v grep | grep artifactory
      register: artifactory_process
      failed_when: false

    - name: Display Artifactory process information
      debug:
        msg: "{{ 'Artifactory process running: Yes' if artifactory_process.rc == 0 else 'Artifactory process running: No' }}"

    - name: Check Artifactory data directory
      stat:
        path: "{{ artifactory_data_dir }}"
      register: artifactory_data_dir_stat

    - name: Display Artifactory data directory information
      debug:
        msg: |
          Artifactory Data Directory:
          ==========================
          Path: {{ artifactory_data_dir }}
          Exists: {{ artifactory_data_dir_stat.stat.exists }}
          Owner: {{ artifactory_data_dir_stat.stat.pw_name | default(artifactory_data_dir_stat.stat.uid) if artifactory_data_dir_stat.stat.exists else 'N/A' }}
          Size: {{ (artifactory_data_dir_stat.stat.size / 1024 / 1024) | round(2) if artifactory_data_dir_stat.stat.exists else 'N/A' }} MB

    - name: Check Artifactory configuration files
      stat:
        path: "{{ item }}"
      register: artifactory_config_files
      loop:
        - "{{ artifactory_data_dir }}/etc/system.yaml"
        - "{{ artifactory_data_dir }}/etc/db.properties"
        - "/etc/systemd/system/artifactory.service"

    - name: Display configuration files status
      debug:
        msg: |
          Configuration Files:
          ===================
          {{ artifactory_data_dir }}/etc/system.yaml: {{ 'Found' if artifactory_config_files.results[0].stat.exists else 'Missing' }}
          {{ artifactory_data_dir }}/etc/db.properties: {{ 'Found' if artifactory_config_files.results[1].stat.exists else 'Missing' }}
          /etc/systemd/system/artifactory.service: {{ 'Found' if artifactory_config_files.results[2].stat.exists else 'Missing' }}

    - name: Check SSL certificates
      stat:
        path: "{{ item }}"
      register: ssl_certificates
      loop:
        - "{{ artifactory_ssl_cert_path }}"
        - "{{ artifactory_ssl_key_path }}"
        - "{{ artifactory_config_dir }}/ssl/ca.crt"
      when: artifactory_ssl_enabled

    - name: Display SSL certificates status
      debug:
        msg: |
          SSL Certificates:
          ================
          {{ artifactory_ssl_cert_path }}: {{ 'Found' if ssl_certificates.results[0].stat.exists else 'Missing' }}
          {{ artifactory_ssl_key_path }}: {{ 'Found' if ssl_certificates.results[1].stat.exists else 'Missing' }}
          {{ artifactory_config_dir }}/ssl/ca.crt: {{ 'Found' if ssl_certificates.results[2].stat.exists else 'Missing' }}
      when: artifactory_ssl_enabled

    - name: Check Artifactory API accessibility
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ artifactory_port }}{{ artifactory_context_path }}/api/system/ping"
        method: GET
        timeout: 10
      register: artifactory_api_check
      failed_when: false

    - name: Display API accessibility
      debug:
        msg: "{{ 'Artifactory API accessible: Yes' if artifactory_api_check.status == 200 else 'Artifactory API accessible: No' }}"

    - name: Get Artifactory system information
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ artifactory_port }}{{ artifactory_context_path }}/api/system/version"
        method: GET
        user: "{{ artifactory_admin_username }}"
        password: "{{ artifactory_admin_password }}"
        force_basic_auth: yes
      register: artifactory_version_info
      failed_when: false
      when: artifactory_api_check.status == 200

    - name: Display Artifactory system information
      debug:
        msg: |
          Artifactory System Information:
          ==============================
          Version: {{ artifactory_version_info.json.version if artifactory_version_info.status == 200 else 'N/A' }}
          Revision: {{ artifactory_version_info.json.revision if artifactory_version_info.status == 200 else 'N/A' }}
          License: {{ artifactory_version_info.json.license if artifactory_version_info.status == 200 else 'N/A' }}
      when: artifactory_api_check.status == 200

    - name: Check Artifactory repositories
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ artifactory_port }}{{ artifactory_context_path }}/api/repositories"
        method: GET
        user: "{{ artifactory_admin_username }}"
        password: "{{ artifactory_admin_password }}"
        force_basic_auth: yes
        status_code: 200
        timeout: 10
      register: artifactory_repositories
      failed_when: false
      when: artifactory_api_check.status == 200

    - name: Display repositories information
      debug:
        msg: |
          Artifactory Repositories:
          ========================
          {% if artifactory_repositories.status is defined and artifactory_repositories.status == 200 %}
          Repository Count: {{ artifactory_repositories.json | length }}
          Repositories:
          {% for repo in artifactory_repositories.json %}
          - {{ repo.key }} ({{ repo.packageType }}/{{ repo.type }})
          {% endfor %}
          {% else %}
          Unable to retrieve repository information
          {% endif %}
      when: artifactory_api_check.status == 200

    - name: Summary
      debug:
        msg: |
          =================================
          ARTIFACTORY VERIFICATION SUMMARY
          =================================
          Service Status: {{ artifactory_service_status.status.ActiveState }}
          Process Running: {{ 'YES' if artifactory_process.rc == 0 else 'NO' }}
          API Responding: {{ 'YES' if artifactory_api_check.status == 200 else 'NO' }}
          
          {% if artifactory_api_check.status == 200 %}
           SUCCESS: Artifactory is running and accessible!
          Access URL: http://{{ ansible_default_ipv4.address }}:{{ artifactory_port }}{{ artifactory_context_path }}
          Admin Username: {{ artifactory_admin_username }}
          {% if artifactory_ssl_enabled %}
          HTTPS URL: https://{{ ansible_default_ipv4.address }}:{{ artifactory_ssl_port }}{{ artifactory_context_path }}
          {% endif %}
          {% else %}
           ISSUES DETECTED: Check service logs and configuration
          {% endif %}