---
- name: PostgreSQL Maintenance and Operations
  hosts: databases
  become: yes
  gather_facts: yes
  
  vars:
    postgresql_version: "15"
    
  tasks:
    - name: Update PostgreSQL statistics
      postgresql_query:
        db: "{{ item }}"
        query: "ANALYZE;"
      become_user: postgres
      loop:
        - "app_production"
        - "app_staging"
      tags:
        - maintenance
        - analyze

    - name: Vacuum databases
      postgresql_query:
        db: "{{ item }}"
        query: "VACUUM;"
      become_user: postgres
      loop:
        - "app_production"
        - "app_staging"
      tags:
        - maintenance
        - vacuum

    - name: Check database sizes
      postgresql_query:
        db: postgres
        query: |
          SELECT 
            datname,
            pg_size_pretty(pg_database_size(datname)) as size
          FROM pg_database 
          WHERE datistemplate = false;
      become_user: postgres
      register: db_sizes
      tags:
        - maintenance
        - monitoring

    - name: Display database sizes
      debug:
        msg: "Database {{ item.datname }}: {{ item.size }}"
      loop: "{{ db_sizes.query_result }}"
      tags:
        - maintenance
        - monitoring

    - name: Check for long-running queries
      postgresql_query:
        db: postgres
        query: |
          SELECT 
            pid,
            now() - pg_stat_activity.query_start AS duration,
            query,
            state
          FROM pg_stat_activity
          WHERE (now() - pg_stat_activity.query_start) > interval '5 minutes'
          AND state = 'active';
      become_user: postgres
      register: long_queries
      tags:
        - maintenance
        - monitoring

    - name: Display long-running queries
      debug:
        msg: "Long running query found: PID {{ item.pid }}, Duration: {{ item.duration }}"
      loop: "{{ long_queries.query_result }}"
      when: long_queries.query_result | length > 0
      tags:
        - maintenance
        - monitoring

    - name: Check connection count
      postgresql_query:
        db: postgres
        query: |
          SELECT 
            count(*) as active_connections,
            (SELECT setting::int FROM pg_settings WHERE name = 'max_connections') as max_connections
          FROM pg_stat_activity;
      become_user: postgres
      register: connection_stats
      tags:
        - maintenance
        - monitoring

    - name: Display connection statistics
      debug:
        msg: "Active connections: {{ connection_stats.query_result[0].active_connections }}/{{ connection_stats.query_result[0].max_connections }}"
      tags:
        - maintenance
        - monitoring

    - name: Check disk usage
      command: df -h /var/lib/postgresql
      register: disk_usage
      changed_when: false
      tags:
        - maintenance
        - monitoring

    - name: Display disk usage
      debug:
        msg: "PostgreSQL disk usage: {{ disk_usage.stdout_lines[1] }}"
      tags:
        - maintenance
        - monitoring

    - name: Rotate PostgreSQL logs
      command: logrotate -f /etc/logrotate.d/postgresql
      tags:
        - maintenance
        - logs

    - name: Clean old backup files (older than retention period)
      find:
        paths: /var/backups/postgresql
        age: "{{ postgresql_backup_retention_days | default(7) }}d"
        file_type: directory
      register: old_backups
      tags:
        - maintenance
        - cleanup

    - name: Remove old backup directories
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_backups.files }}"
      tags:
        - maintenance
        - cleanup

    - name: Update PostgreSQL package (if available)
      apt:
        name: 
          - "postgresql-{{ postgresql_version }}"
          - "postgresql-client-{{ postgresql_version }}"
          - "postgresql-contrib-{{ postgresql_version }}"
        state: latest
        update_cache: yes
      notify:
        - restart postgresql
      tags:
        - maintenance
        - update

    - name: Check for PostgreSQL configuration changes
      command: "sudo -u postgres psql -c 'SELECT name, setting, pending_restart FROM pg_settings WHERE pending_restart = true;'"
      register: pending_restart
      changed_when: false
      tags:
        - maintenance
        - config

    - name: Display settings requiring restart
      debug:
        msg: "Settings requiring restart: {{ pending_restart.stdout }}"
      when: "'(0 rows)' not in pending_restart.stdout"
      tags:
        - maintenance
        - config

    - name: Create maintenance report
      copy:
        content: |
          PostgreSQL Maintenance Report - {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          ===============================================================================
          
          Host: {{ inventory_hostname }}
          PostgreSQL Version: {{ postgresql_version }}
          
          Database Sizes:
          {% for db in db_sizes.query_result %}
          - {{ db.datname }}: {{ db.size }}
          {% endfor %}
          
          Connection Statistics:
          - Active: {{ connection_stats.query_result[0].active_connections }}
          - Maximum: {{ connection_stats.query_result[0].max_connections }}
          - Usage: {{ (connection_stats.query_result[0].active_connections / connection_stats.query_result[0].max_connections * 100) | round(1) }}%
          
          Disk Usage:
          {{ disk_usage.stdout }}
          
          Long Running Queries: {{ long_queries.query_result | length }}
          {% if long_queries.query_result | length > 0 %}
          {% for query in long_queries.query_result %}
          - PID {{ query.pid }}: {{ query.duration }}
          {% endfor %}
          {% endif %}
          
          Maintenance Actions Performed:
          - Database analysis completed
          - Vacuum operations completed
          - Log rotation performed
          - Old backups cleaned ({{ old_backups.files | length }} removed)
          
        dest: "/var/log/postgresql-maintenance-{{ ansible_date_time.date }}.log"
        owner: postgres
        group: postgres
        mode: '0644'
      tags:
        - maintenance
        - report

  handlers:
    - name: restart postgresql
      systemd:
        name: postgresql
        state: restarted
        daemon_reload: yes